<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">

<head>

<title>Error 404: Document not found!</title>
  

 <link href="/sys/style-sheets/sys-course.css" rel="stylesheet"
       type="text/css"/>
 <link href="/sys/style-sheets/sys-fixed.css" rel="stylesheet"
       type="text/css"/>
 <link href="/sys/style-sheets/sys-styles.css" rel="stylesheet"
       type="text/css"/>
 <link href="/sys/style-sheets/sys-header.css" rel="stylesheet"
       type="text/css"/>
 <link href="/sys/style-sheets/sys-print.css" media="print" rel="stylesheet"
       type="text/css"/>


</head>

<body>
<div class="forest">
 <div class="header">
  <div class="floatleft">
   <a href="http://www.bham.ac.uk/">
    <img src="/sys/images/University-of-Birmingham-logo.gif"
         alt="University of Birmingham" width="141" height="34" />
   </a>
  </div>
  <div class="searchboxandbtn">
    <form action="http://www.search.bham.ac.uk/search" method="get">
      <div>
        <input type="hidden" name="output" value="xml_no_dtd"/>
        <input type="hidden" name="ie" value="UTF-8"/>
        <input type="hidden" name="oe" value="UTF-8"/>
        <input type="hidden" name="client" value="computer_science"/>
        <input type="hidden" name="site" value="computer_science"/>
        <input type="hidden" name="proxystylesheet" value="computer_science"/>
      </div>
      <div class="search">
        <label for="searchbox" class="skipitem">Search</label>
        <input size="15" maxlength="30" name="q" id="searchbox"
               value="Search" 
               onfocus="if(this.value=='Search') {this.value='';}" 
               onblur="if(this.value =='') {this.value='Search';}" />
      </div>
      <div class="searchbtn">
        <input type="image" src="/sys/images/search-btn.gif"
               alt="Do the search" />
      </div>
    </form>
  </div>
  <div class="title">
   <h1>School of Computer Science<br/>Personal Web Page</h1>

  <!-- Breadcrumb Trail -->

 <div class="forest">
  <div class="breadcrumbs">
   <div class="floatleft">
    <ul>
     <li class="skipitem">
      <a href="#skip">Skip past menu to page content</a>
     </li>
     <li class="firstitem"><a href="/">Home</a>&nbsp;&raquo;</li> 
     <li><a href="/sys/errordocs">Errordocs</a>&nbsp;&raquo;</li> 
     <li><a href="/sys/errordocs/404.php">404</a>&nbsp;&raquo;</li> 
    </ul>
   </div>
  </div>
 </div>

  </div>

 </div>
</div>

  <!-- Button Tabs -->

 <div class="forest">
  <div class="menubar">
   <div class="skipitem">
     <p><a href="#skip">Skip past menu to page content</a></p>
    </div>
   <div class="menuitemfirst">
    <div class="floatleft">
      <img src="/sys/images/left-of-tab.gif" alt="" width="2" height="21" />
    </div>
    <div class="leftiteminactive">
      <img src="/sys/images/doublearrow.gif" alt="" width="7" height="5" />
        <a href="http://www.cs.bham.ac.uk/">Computer Science</a>
    </div>
    <div class="floatleft">
      <img src="/sys/images/right-of-tab.gif" alt="" width="5" height="21" />
    </div>
   </div>

   <div class="menuitem">
    <div class="floatleft">
      <img src="/sys/images/left-of-tab.gif" alt="" width="2" height="21" />
    </div>
    <div class="leftiteminactive">
      <img src="/sys/images/doublearrow.gif" alt="" width="7" height="5" />
        <a href="/~tpc">Home</a>
    </div>
    <div class="floatleft">
      <img src="/sys/images/right-of-tab.gif" alt="" width="5" height="21" />
    </div>
   </div>

    <div class="menubottom"></div>
   </div>
  </div>
    
  <!-- Start of Main Page -->
  <div class="body">

  <!-- Start of the Sidebar -->
  <div >
  <div class="sidebar">
   <ul>
    <li class="skipitem">
      <a href="#skip">Skip past menu to page content</a>
    </li>
<li>
<a href="http://www.cs.bham.ac.uk/">School Homepage
</a>
</li>
   </ul>
  </div>
  </div>

  <!-- End of the Sidebar -->
  <a name="skip"></a>
  <div class="forest">
  <div class="ubcontent">

  <div class="ubcoursefullwidth">
   <div class="ubcourseline">&nbsp;</div>
   <h1>Error 404: Document not found!</h1>
   <hr/>

<p>The page you are looking for could not be found. This might be because you incorrectly typed the address of the page, or because the page has been moved or deleted.</p>

<p>We've recently restructured our website, so if you followed a link then we might have moved the page. We suggest you try searching the site.</p>

<p>Page error generated by server: staffweb.cs.bham.ac.uk, server URI: /~tpc/AE/src/IT.java</p>

</div>
  </div>
  </div>
  </div>

  <!-- End of Main Page -->

  <div class="footer">
&nbsp;
  </div>


</body>
</html>